#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestApp.Resource", IsApplication=true)]

namespace TestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int circleCrop = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int colorScheme = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int imageAspectRatio = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int imageAspectRatioAdjust = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int scopeUris = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int common_action_bar_splitter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int common_google_signin_btn_text_dark = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int common_google_signin_btn_text_dark_default = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int common_google_signin_btn_text_dark_disabled = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int common_google_signin_btn_text_dark_focused = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int common_google_signin_btn_text_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int common_google_signin_btn_text_light = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int common_google_signin_btn_text_light_default = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int common_google_signin_btn_text_light_disabled = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int common_google_signin_btn_text_light_focused = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int common_google_signin_btn_text_light_pressed = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int common_plus_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int common_plus_signin_btn_text_dark_default = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int common_plus_signin_btn_text_dark_disabled = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int common_plus_signin_btn_text_dark_focused = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int common_plus_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int common_plus_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int common_plus_signin_btn_text_light_default = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int common_plus_signin_btn_text_light_disabled = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int common_plus_signin_btn_text_light_focused = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int common_plus_signin_btn_text_light_pressed = 2130837524;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int common_full_open_on_phone = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int common_google_signin_btn_icon_dark = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int common_google_signin_btn_icon_dark_disabled = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int common_google_signin_btn_icon_dark_focused = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int common_google_signin_btn_icon_dark_normal = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int common_google_signin_btn_icon_dark_pressed = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int common_google_signin_btn_icon_light = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int common_google_signin_btn_icon_light_disabled = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int common_google_signin_btn_icon_light_focused = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int common_google_signin_btn_icon_light_normal = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int common_google_signin_btn_icon_light_pressed = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int common_google_signin_btn_text_dark = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int common_google_signin_btn_text_dark_disabled = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int common_google_signin_btn_text_dark_focused = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int common_google_signin_btn_text_dark_normal = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int common_google_signin_btn_text_dark_pressed = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int common_google_signin_btn_text_light = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int common_google_signin_btn_text_light_disabled = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int common_google_signin_btn_text_light_focused = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int common_google_signin_btn_text_light_normal = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int common_google_signin_btn_text_light_pressed = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int common_ic_googleplayservices = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int common_plus_signin_btn_icon_dark = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int common_plus_signin_btn_icon_dark_focused = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int common_plus_signin_btn_icon_dark_normal = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int common_plus_signin_btn_icon_dark_pressed = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int common_plus_signin_btn_icon_light = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int common_plus_signin_btn_icon_light_disabled = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int common_plus_signin_btn_icon_light_focused = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int common_plus_signin_btn_icon_light_normal = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int common_plus_signin_btn_icon_light_pressed = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int common_plus_signin_btn_text_dark = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int common_plus_signin_btn_text_dark_disabled = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int common_plus_signin_btn_text_dark_focused = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int common_plus_signin_btn_text_dark_normal = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int common_plus_signin_btn_text_dark_pressed = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int common_plus_signin_btn_text_light = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int common_plus_signin_btn_text_light_disabled = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int common_plus_signin_btn_text_light_focused = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int common_plus_signin_btn_text_light_normal = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int common_plus_signin_btn_text_light_pressed = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int Icon = 2130903082;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int adjust_height = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int adjust_width = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int auto = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int dark = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int icon_only = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int light = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int myButton = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int none = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int standard = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int wide = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int Main = 2131099648;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int accept = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int auth_google_play_services_client_facebook_display_name = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int auth_google_play_services_client_google_display_name = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int common_google_play_services_api_unavailable_text = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int common_google_play_services_enable_button = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int common_google_play_services_enable_text = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int common_google_play_services_enable_title = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int common_google_play_services_install_button = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int common_google_play_services_install_text_phone = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int common_google_play_services_install_text_tablet = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int common_google_play_services_install_title = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int common_google_play_services_invalid_account_text = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int common_google_play_services_invalid_account_title = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int common_google_play_services_network_error_text = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int common_google_play_services_network_error_title = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int common_google_play_services_notification_ticker = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int common_google_play_services_restricted_profile_text = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int common_google_play_services_restricted_profile_title = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int common_google_play_services_sign_in_failed_text = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int common_google_play_services_sign_in_failed_title = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int common_google_play_services_unknown_issue = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int common_google_play_services_unsupported_text = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int common_google_play_services_unsupported_title = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int common_google_play_services_update_button = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int common_google_play_services_update_text = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int common_google_play_services_update_title = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int common_google_play_services_updating_text = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int common_google_play_services_updating_title = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int common_google_play_services_wear_update_text = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int common_open_on_phone = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int common_signin_button_text = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int common_signin_button_text_long = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int create_calendar_message = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int create_calendar_title = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int decline = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int hello = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int store_picture_message = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int store_picture_title = 2131165222;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int Theme_IAPTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002 }
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			// aapt resource value: { 0x7F010004,0x7F010006,0x7F010007 }
			public static int[] LoadingImageView = new int[] {
					2130771972,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public const int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F010003,0x7F010005,0x7F010008 }
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771973,
					2130771976};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
